import { NextPage } from 'next';
import Head from 'next/head';
import { Cliente } from '@prisma/client';
import { useQuery } from '@apollo/client';
import { GET_CLIENTES } from '@graphql/client/clientes/queries/clientes';
/*
const prisma = new PrismaClient();

export async function getServerSideProps() {
  return {
    props: {}, // will be passed to the page component as props
  };
}
*/
const Home: NextPage = () => {
  const { data, loading } = useQuery(GET_CLIENTES);
  if (loading) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>CLIENTES ENCONTRADOS</h1>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Identificación</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Servicios</th>
            </tr>
          </thead>
          <tbody>
            {data.clientes.map((c: Cliente) => (
              <tr>
                <td>{c.id}</td>
                <td>{c.documento}</td>
                <td>
                  {c.primerNombre} {c.segundoNombre}
                </td>
                <td>
                  {c.primerApellido} {c.segundoApellido}
                </td>
                <td>Mas...</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
export default Home;
