import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient();

export async function getServerSideProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}



const Home:NextPage =()=> {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
